# Spherical Harmonics

In [152]:
# Import necessary libraries
import matplotlib.pyplot as plt
from matplotlib import cm, colors
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from scipy.special import sph_harm
from matplotlib import animation
from matplotlib.colors import LightSource
from IPython import display
import matplotlib

In [153]:
matplotlib.use('TkAgg')

In [154]:
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2*np.pi, 50)
theta, phi = np.meshgrid(theta, phi)

# The Cartesian coordinates of the unit sphere
x = np.sin(theta) * np.cos(phi)
y = np.sin(theta) * np.sin(phi)
z = np.cos(theta)

def get_SphHarm(l, m, component):
    ## Calculate the spherical harmonic Y(l,m) and normalize to [0,1]
    if component=='abs':
        rx = getattr(sph_harm(m, l, phi, theta), 'real')
        ix = getattr(sph_harm(m, l, phi, theta), 'imag')
        fcolors = np.sqrt(rx*rx+ix*ix)
    else:
        fcolors = getattr(sph_harm(m, l, phi, theta), component)
    wavefun = fcolors
    fmax, fmin = fcolors.max(), fcolors.min()
    if (fmax==fmin):
        fcolors = (fcolors - fmin)
    else:
        fcolors = (fcolors - fmin)/(fmax - fmin)
    ls = LightSource(180, 45)
    rgb = ls.shade(fcolors, cmap=cm.seismic, vert_exag=0.1, blend_mode='soft')
    if np.unique(wavefun).size==1:
        rgb = np.tile(np.array([1,0,0,1]), (rgb.shape[0],rgb.shape[1],1))
    return wavefun,rgb
    
def generate_animation(rgb, r, fig, ax):
    ## Generate animation
    def init():
        for rgbi,axi,ri in zip(rgb,ax,r):
            ri = np.abs(np.squeeze(np.array(ri)))
            axi.plot_surface(x, y, z,  rstride=1, cstride=1, facecolors=rgbi, shade=False)
        return fig,
    def animate(i):
        for axi in ax:
            axi.view_init(elev=30, azim=0+10*i)
        return fig,
    
    ani = animation.FuncAnimation(fig, animate, init_func=init,
                           frames=36, interval=50, blit=True)
    return ani

def generate_animation2(rgb, r, fig, ax):
    ## Generate animation
    def init():
        for rgbi,axi,ri in zip(rgb,ax,r):
            ri = np.abs(np.squeeze(np.array(ri)))
            axi.plot_surface(x*ri, y*ri, z*ri,  rstride=1, cstride=1, facecolors=rgbi, shade=False)
        return fig,
    def animate(i):
        for axi in ax:
            axi.view_init(elev=30, azim=0+10*i)
        return fig,
    ani = animation.FuncAnimation(fig, animate, init_func=init,
                           frames=36, interval=50, blit=True)
    return ani

def createAllHarmonics(l):
    plt.rcParams['figure.facecolor'] = '#d3d3d3'
    for m in range(-l,l+1):
        print(l,m)
        fig = plt.figure(figsize=plt.figaspect(0.5))

        realR,realPart = get_SphHarm(l, m, 'real')
        imagR,imagPart = get_SphHarm(l, m, 'imag')
        absR,absValue = get_SphHarm(l, m, 'abs')
        absR2 = absR**2


        realAx = fig.add_subplot(131, projection='3d')
        imagAx = fig.add_subplot(132, projection='3d')
        absAx = fig.add_subplot(133, projection='3d')
        allaxs = [realAx, imagAx,absAx]

        for eachAx in allaxs:
            eachAx.set_axis_off()
            eachAx.set_facecolor(color='#d3d3d3')

        aniflat = generate_animation([realPart,imagPart,absValue],[realR,imagR,absR],fig,allaxs)
        anidist = generate_animation2([realPart,imagPart,absValue],[realR,imagR,absR],fig,allaxs)
        #aniabs = generate_animation2([absValue,absValue],[absR,absR2],fig,allaxs)
        ## Display animation
        print('Drawing ...')

        
        path = "./output/"
        FFwriter = animation.FFMpegWriter(fps=30, codec="libx264")     
        anidist.save(path+f"l{l}m{m}dist.mp4", writer = FFwriter)
        aniflat.save(path+f"l{l}m{m}flat.mp4", writer = FFwriter)

        #video = ani.to_html5_video()
        #html = display.HTML(video)
        #display.HTML(video)
        #display.display(html)
        plt.close(fig)
    print("done")

In [155]:
for l in range(1,6):
    createAllHarmonics(l)

1 -1
[[0.49948582 0.53157036 0.56352305 ... 0.56352305 0.53157036 0.49948582]
 [0.49948582 0.53130694 0.56299731 ... 0.56299731 0.53130694 0.49948582]
 [0.49948582 0.53052103 0.56142871 ... 0.56142871 0.53052103 0.49948582]
 ...
 [0.49948582 0.53052103 0.56142871 ... 0.56142871 0.53052103 0.49948582]
 [0.49948582 0.53130694 0.56299731 ... 0.56299731 0.53130694 0.49948582]
 [0.49948582 0.53157036 0.56352305 ... 0.56352305 0.53157036 0.49948582]]
[[0.5        0.5        0.5        ... 0.5        0.5        0.5       ]
 [0.5        0.49589923 0.49181531 ... 0.49181531 0.49589923 0.5       ]
 [0.5        0.49186579 0.48376501 ... 0.48376501 0.49186579 0.5       ]
 ...
 [0.5        0.50813421 0.51623499 ... 0.51623499 0.50813421 0.5       ]
 [0.5        0.50410077 0.50818469 ... 0.50818469 0.50410077 0.5       ]
 [0.5        0.5        0.5        ... 0.5        0.5        0.5       ]]
[[0.         0.06410316 0.1279429  ... 0.1279429  0.06410316 0.        ]
 [0.         0.06410316 0.1279429 

CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '576x288', '-pix_fmt', 'rgba', '-r', '30', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'libx264', '-y', './output/l1m-1dist.mp4']' returned non-zero exit status 255.